export const ANIMATION_DELAYS = {
  INITIAL_LOAD: 1500,
  STAGGER_ITEM: 0.08,
} as const;

export const ANIMATION_DURATIONS = {
  GALLERY_FADE_IN: 0.6,
  ITEM_SLIDE_IN: 0.4,
} as const;

export const GALLERY_CONFIG = {
  EAGER_LOAD_COUNT: 3,
  DEFAULT_IMAGE_WIDTH: 300,
  DEFAULT_IMAGE_HEIGHT: 400,
  MODAL_IMAGE_WIDTH: 600,
  MODAL_IMAGE_HEIGHT: 800,
} as const;
