export const paintings = [
  {
    id: 'Eyes Wide Open',
    src: '/img/allEyes.JPG',
    alt: 'watercolor eyes and flowers',
    title: 'Eyes Wide Open',
    width: 300,
    height: 400,
  },
  {
    id: 'Flowers Make Us Girl',
    src: '/img/girlWithFlowers.JPG',
    alt: 'watercolor girl and flowers',
    title: 'Flowers Make Us Girl',
    width: 300,
    height: 400,
  },
  {
    id: 'Flowers Make Us Girl-2',
    src: '/img/girlWithSunflower.JPG',
    alt: 'girl with sunflower',
    title: 'Flowers Make Us Girl-2',
    width: 300,
    height: 400,
  },
  {
    id: 'The Hometown',
    src: '/img/BluePlanet.JPG',
    alt: 'watercolor earth',
    title: 'The Hometown',
    width: 300,
    height: 400,
  },
  {
    id: 'The Night',
    src: '/img/MoonZan.JPG',
    alt: 'watercolor moon with flowers',
    title: 'The Night',
    width: 300,
    height: 400,
  },
  {
    id: 'In a Dream',
    src: '/img/in-a-dream.jpg',
    alt: 'giant purple flowers',
    title: 'In a Dream',
    width: 300,
    height: 400,
  },
];
